name: NISTKAT OV16_160_64_pkc_skc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.impl }} ${{ matrix.cc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc:
          - gcc
          - clang
        impl:
          - ref
          - avx2
          - ssse3
          - amd64
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: make KAT=1 PARAM=1 VARIANT=3 PROJ=${{ matrix.impl }} check-NISTKAT
      env:
        CC: ${{ matrix.cc }}
